Fail PR check if workflow failed

diff --git a/.github/workflows/pr.yaml b/.github/workflows/pr.yaml
--- a/.github/workflows/pr.yaml
+++ b/.github/workflows/pr.yaml
@@ -145,6 +145,11 @@ jobs:
   accept-pr:
     needs: [ build, test, smoke-test, muzzle ]
     runs-on: ubuntu-latest
+    if: always()
     steps:
-      - name: Success
-        run: echo Build successful
+      # run this action to get workflow conclusion
+      # You can get conclusion by env (env.WORKFLOW_CONCLUSION)
+      - uses: technote-space/workflow-conclusion-action@v1
+      - name: Fail build
+        if: env.WORKFLOW_CONCLUSION == 'failure' # notify only if failure
+        run: exit 1
