Auto-update contrib on release (#6351)

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -6,43 +6,43 @@ jobs:
   assemble:
     uses: ./.github/workflows/reusable-assemble.yml
 
-  test-java8:
-    uses: ./.github/workflows/reusable-test-8.yml
+  test:
+    uses: ./.github/workflows/reusable-test.yml
 
-  test-java11:
-    uses: ./.github/workflows/reusable-test-11.yml
-
-#   test-latest-deps is intentionally not included in the release workflows
-#   because any time a new library version is released to maven central
-#   it can fail due to test code incompatibility with the new library version,
-#   or due to slight changes in emitted telemetry
+  # test-latest-deps is intentionally not included in the release workflows
+  # because any time a new library version is released to maven central
+  # it can fail due to test code incompatibility with the new library version,
+  # or due to slight changes in emitted telemetry
 
   smoke-test:
     uses: ./.github/workflows/reusable-smoke-test.yml
 
-#   muzzle is intentionally not included in the release workflows
-#   because any time a new library version is released to maven central it can fail,
-#   and this is not a reason to hold up the release
+  # muzzle is intentionally not included in the release workflows
+  # because any time a new library version is released to maven central it can fail,
+  # and this is not a reason to hold up the release
 
   gradle-plugins:
     uses: ./.github/workflows/reusable-gradle-plugins.yml
 
-# removed this for now until we decide what to do with the extenstions
-#  examples:
-#    uses: ./.github/workflows/reusable-examples.yml
+  examples:
+    uses: ./.github/workflows/reusable-examples.yml
 
   release:
     needs:
       - assemble
-      - test-java8
-      - test-java11
+      - test
       - smoke-test
       - gradle-plugins
-#      - examples
+      - examples
     outputs:
       version: ${{ steps.create-github-release.outputs.version }}
     runs-on: ubuntu-latest
     steps:
+      - run: |
+          if [[ $GITHUB_REF_NAME != release/* ]]; then
+            echo this workflow should only be run against release branches
+            exit 1
+          fi
 
       - uses: actions/checkout@v3
 
@@ -77,6 +77,15 @@ jobs:
         with:
           ref: main
 
+      - run: |
+          if [[ $VERSION == *.0 ]]; then
+            # not making a patch release
+            if ! grep --quiet "^## Version $VERSION " CHANGELOG.md; then
+              echo the pull request generated by prepare-release-branch.yml needs to be merged first
+              exit 1
+            fi
+          fi
+
         # back to the release branch
       - uses: actions/checkout@v3
         with:
@@ -88,11 +97,70 @@ jobs:
           distribution: temurin
           java-version: 17
 
-      - name: Setup Gradle
+      - name: Build and publish artifacts
         uses: gradle/gradle-build-action@v2
+        with:
+          arguments: assemble publishToSonatype closeAndReleaseSonatypeStagingRepository
+        env:
+          SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
+          SONATYPE_KEY: ${{ secrets.SONATYPE_KEY }}
+          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
+          GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
 
-      - name: Execute Gradle build
-        run: ./gradlew build
+      - name: Build and publish gradle plugins
+        uses: gradle/gradle-build-action@v2
+        env:
+          SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
+          SONATYPE_KEY: ${{ secrets.SONATYPE_KEY }}
+          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
+          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
+          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
+          GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
+        with:
+          # Don't use publishToSonatype since we don't want to publish the marker artifact
+          arguments: build publishPlugins publishPluginMavenPublicationToSonatypeRepository closeAndReleaseSonatypeStagingRepository
+          build-root-directory: gradle-plugins
+
+      - name: Generate release notes
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          # conditional blocks not indented because of the heredoc
+          if [[ $VERSION == *.0 ]]; then
+          cat > /tmp/release-notes.txt << EOF
+          This release targets the OpenTelemetry SDK $VERSION.
+
+          Note that all artifacts other than \`io.opentelemetry.javaagent:opentelemetry-javaagent\` have the \`-alpha\` suffix attached to their version number, reflecting that they are still alpha quality and will continue to have breaking changes. Please see the [VERSIONING.md](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/VERSIONING.md#opentelemetry-java-instrumentation-versioning) for more details.
+
+          EOF
+          else
+          cat > /tmp/release-notes.txt << EOF
+          This is a patch release on the previous $PRIOR_VERSION release, fixing the issue(s) below.
+
+          EOF
+          fi
+
+          # CHANGELOG_SECTION.md is also used at the end of the release workflow
+          # for copying the change log updates to main
+          sed -n "0,/^## Version $VERSION /d;/^## Version /q;p" CHANGELOG.md \
+            > /tmp/CHANGELOG_SECTION.md
+
+          # the complex perl regex is needed because markdown docs render newlines as soft wraps
+          # while release notes render them as line breaks
+          perl -0pe 's/(?<!\n)\n *(?!\n)(?![-*] )(?![1-9]+\. )/ /g' /tmp/CHANGELOG_SECTION.md \
+            >> /tmp/release-notes.txt
+
+          # conditional block not indented because of the heredoc
+          if [[ $VERSION == *.0 ]]; then
+          cat >> /tmp/release-notes.txt << EOF
+          ### 🙇 Thank you
+
+          This release was possible thanks to the following contributors who shared their brilliant ideas and awesome pull requests:
+
+          EOF
+
+          .github/scripts/generate-release-contributors.sh v$PRIOR_VERSION >> /tmp/release-notes.txt
+          fi
 
       - id: create-github-release
         name: Create GitHub release
@@ -102,7 +170,102 @@ jobs:
           cp javaagent/build/libs/opentelemetry-javaagent-${VERSION}.jar opentelemetry-javaagent.jar
           gh release create --target $GITHUB_REF_NAME \
                             --title "Version $VERSION" \
+                            --notes-file /tmp/release-notes.txt \
+                            --discussion-category announcements \
                             v$VERSION \
                             opentelemetry-javaagent.jar
 
           echo "::set-output name=version::$VERSION"
+
+      - uses: actions/checkout@v3
+        with:
+          # the step below is creating a pull request against main
+          ref: main
+
+      - name: Copy change log updates to main
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          if [[ $VERSION == *.0 ]]; then
+            # this was not a patch release, so the version exists already in the CHANGELOG.md
+
+            # update the release date
+            date=$(gh release view v$VERSION --json publishedAt --jq .publishedAt | sed 's/T.*//')
+            sed -Ei "s/## Version $VERSION .*/## Version $VERSION ($date)/" CHANGELOG.md
+
+            # the entries are copied over from the release branch to support workflows
+            # where change log entries may be updated after preparing the release branch
+
+            # copy the portion above the release, up to and including the heading
+            sed -n "0,/^## Version $VERSION ($date)/p" CHANGELOG.md > /tmp/CHANGELOG.md
+
+            # copy the release notes
+            cat /tmp/CHANGELOG_SECTION.md >> /tmp/CHANGELOG.md
+
+            # copy the portion below the release
+            sed -n "0,/^## Version $VERSION /d;0,/^## Version /{/^## Version/!d};p" CHANGELOG.md \
+              >> /tmp/CHANGELOG.md
+
+            # update the real CHANGELOG.md
+            cp /tmp/CHANGELOG.md CHANGELOG.md
+          else
+            # this was a patch release, so the version does not exist already in the CHANGELOG.md
+
+            # copy the portion above the top-most release, not including the heading
+            sed -n "0,/^## Version /{ /^## Version /!p }" CHANGELOG.md > /tmp/CHANGELOG.md
+
+            # add the heading
+            date=$(gh release view v$VERSION --json publishedAt --jq .publishedAt | sed 's/T.*//')
+            echo "## Version $VERSION ($date)" >> /tmp/CHANGELOG.md
+
+            # copy the release notes
+            cat /tmp/CHANGELOG_SECTION.md >> /tmp/CHANGELOG.md
+
+            # copy the portion starting from the top-most release
+            sed -n "/^## Version /,\$p" CHANGELOG.md >> /tmp/CHANGELOG.md
+
+            # update the real CHANGELOG.md
+            cp /tmp/CHANGELOG.md CHANGELOG.md
+          fi
+
+      - name: Use CLA approved github bot
+        run: .github/scripts/use-cla-approved-github-bot.sh
+
+      - name: Create pull request against main
+        env:
+          # not using secrets.GITHUB_TOKEN since pull requests from that token do not run workflows
+          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
+        run: |
+          message="Copy change log updates from $GITHUB_REF_NAME"
+          body="Copy log updates from \`$GITHUB_REF_NAME\`."
+          branch="copy-change-log-updates-from-${GITHUB_REF_NAME//\//-}"
+
+          if [[ $VERSION == *.0 ]]; then
+            if git diff --quiet; then
+              echo there are no updates needed to the change log on main, not creating pull request
+              exit 0 # success
+            fi
+          fi
+
+          git commit -a -m "$message"
+          git push origin HEAD:$branch
+          gh pr create --title "$message" \
+                       --body "$body" \
+                       --head $branch \
+                       --base main
+
+  create-operator-pull-request:
+    needs: release
+    uses: ./.github/workflows/reusable-create-operator-pull-request.yml
+    with:
+      version: ${{ needs.release.outputs.version }}
+    secrets:
+      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
+
+  create-java-contrib-pull-request:
+    needs: release
+    uses: ./.github/workflows/reusable-create-java-contrib-pull-request.yml
+    with:
+      version: ${{ needs.release.outputs.version }}
+    secrets:
+      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
